driver:
  name: terraform
  variable_files:
    - testing.tfvars

provisioner:
  name: terraform

platforms:
  - name: ubuntu

verifier:
  name: terraform
  systems:
    - name: default
      backend: ssh
      user: ubuntu
      hosts_output: public_dns 
      #PATH TO YOUR PRIVATE KEY(key.pem)
      key_files:
      - /Users/martinhristov/Tasks/TerraformLearn/tf_aws_cluster/terraformKitchen.pem
      
suites:
  - name: default
